### PR TITLE
fix: include H5086 in alternate power state configuration

### LINKED ISSUE #186: Power state change in HA for Goveee H5086 plug doesn't work
### Govee Device SKU

H5086

### Govee2MQTT Version

2024.04.29-30cf7732

### Describe the issue

When attempting to turn a Govee H5086 device on-or off, the action does not work -- The symptoms are identical to what was seen in https://github.com/wez/govee2mqtt/issues/29

### Startup Diagnostics

Specific log event provided in Additional Logs

### Additional Logs

```
[2024-05-05T06:56:57 INFO  govee::service::hass] powerSwitch for 0F7B6074F49E2D34: OFF
[2024-05-05T06:56:57 INFO  govee::service::state] Using Platform API to set Upstairs Landing Plug (0F:7B:60:74:F4:9E:2D:34 H5086) power state
[2024-05-05T06:56:58 INFO  govee::platform_api] control_device result: ControlDeviceResponse { request_id: "uuid", code: 200, message: "success", capability: ControlDeviceResponseCapability { kind: OnOff, instance: "powerSwitch", value: Number(0), state: Object {"status": String("success")} } }
[2024-05-05T06:57:02 INFO  govee::service::hass] powerSwitch for 0F7B6074F49E2D34: ON
[2024-05-05T06:57:02 INFO  govee::service::state] Using Platform API to set Upstairs Landing Plug (0F:7B:60:74:F4:9E:2D:34 H5086) power state
[2024-05-05T06:57:02 INFO  govee::platform_api] control_device result: ControlDeviceResponse { request_id: "uuid", code: 200, message: "success", capability: ControlDeviceResponseCapability { kind: OnOff, instance: "powerSwitch", value: Number(1), state: Object {"status": String("success")} } }
[2024-05-05T06:57:03 INFO  govee::service::state] Polling Upstairs Landing Plug (0F:7B:60:74:F4:9E:2D:34 H5086) to get latest state after control
[2024-05-05T06:57:03 INFO  govee::service::state] requesting update via Platform API Upstairs Landing Plug (0F:7B:60:74:F4:9E:2D:34 H5086) Some(DeviceState { on: true, light_on: None, online: None, kelvin: 0, color: DeviceColor { r: 0, g: 0, b: 0 }, brightness: 0, scene: None, source: "AWS IoT API", updated: 2024-05-05T10:45:39.961444248Z })
[2024-05-05T06:57:07 INFO  govee::service::state] Polling Upstairs Landing Plug (0F:7B:60:74:F4:9E:2D:34 H5086) to get latest state after control
[2024-05-05T06:57:07 INFO  govee::service::state] requesting update via Platform API Upstairs Landing Plug (0F:7B:60:74:F4:9E:2D:34 H5086) Some(DeviceState { on: true, light_on: None, online: None, kelvin: 0, color: DeviceColor { r: 0, g: 0, b: 0 }, brightness: 0, scene: None, source: "AWS IoT API", updated: 2024-05-05T10:56:58.376118756Z })
```

### Home Assistant Logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by cmgrayb**
Hoping this will correct the on/off actions on H5086 switches.

closes #186

### CODE REVIEW

**Comment by wez** [comment]
Have you tested this to confirm that it does work?

**Comment by cmgrayb** [comment]
Admittedly, I have not.  I have found no way to put the add-on container directly on my local network so that it can see the broadcasts from the Govee devices and still have access to the MQTT broker.

**Comment by cmgrayb** [comment]
Update: I have found a way, and it is not working.  I am putting this back in draft while testing continues.

**Comment by cmgrayb** [comment]
My apologies, but I'm backing out at this point.  Add-on local testing is broken right now at a fundamental level, and I'm in over my head between Rust and Bluetooth, neither of which are in my usual wheelhouse.  Love your add-on, I was really looking forward to helping.  Maybe next time.

**Pull request closed without merging**
