### PR TITLE
Update quirks for H5051, H5103, H5179.

### LINKED ISSUE #163: H5179 - Temperature Readings are not valid.
### Govee Device SKU

H5179

### Govee2MQTT Version

2024.01.24-ea3cd430 

### Describe the issue

Sensor.entityname brings back values of 31.xx or 32.xx.     Running HAOS  2024.4.0 with the MQTT Integration.    Mosquitto broker add-in version: 6.4.0

Everything was working fine for a few months until HAOS updates were applied about three weeks ago.

add-in is configured for temp units in F

Sensor report tempure correctly via the Govee app for IOS.

### Startup Diagnostics

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
GOVEE_API_KEY=REDACTED
GOVEE_MQTT_HOST=192.168.0.240
GOVEE_TEMPERATURE_SCALE=F
GOVEE_EMAIL=REDACTED
GOVEE_PASSWORD=REDACTED
GOVEE_MQTT_PASSWORD=REDACTED
GOVEE_MQTT_USER=addons
GOVEE_MQTT_PORT=1883
++ cd /app
++ exec /app/govee serve
[2024-04-03T22:45:29 INFO  govee::commands::serve] Starting service. version 2024.01.24-ea3cd430
[2024-04-03T22:45:29 INFO  govee::commands::serve] Querying platform API for device list
[2024-04-03T22:45:29 INFO  govee::commands::serve] Querying undocumented API for device + room list
[2024-04-03T22:45:29 INFO  govee::service::iot] Connected to IoT: CONNACK code 0: Connection Accepted.
[2024-04-03T22:45:29 INFO  govee::commands::serve] Starting LAN discovery
[2024-04-03T22:45:29 INFO  govee::commands::serve] Waiting 10 seconds for LAN API discovery
[2024-04-03T22:45:29 INFO  govee::service::iot] IoT (re)connected with status CONNACK code 0: Connection Accepted.
[2024-04-03T22:45:39 INFO  govee::commands::serve] Devices returned from Govee's APIs
[2024-04-03T22:45:39 INFO  govee::commands::serve] LG Freezer (13:1A:18:1F:68:13:60:82 H5179)
[2024-04-03T22:45:39 INFO  govee::commands::serve]   Platform API: devices.types.thermometer. supports_rgb=false supports_brightness=false
[2024-04-03T22:45:39 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-04-03T22:45:39 INFO  govee::commands::serve]   Undoc: room=Some("Laundry") supports_iot=false ble_only=true
[2024-04-03T22:45:39 INFO  govee::commands::serve]   Quirk { sku: "H5179", icon: "mdi:thermometer", supports_rgb: false, supports_brightness: false, color_temp_range: None, avoid_platform_api: false, ble_only: false, lan_api_capable: false, device_type: Thermometer, platform_temperature_sensor_units: Some(CelsiusTimes100), platform_humidity_sensor_units: Some(RelativePercentTimes100), iot_api_supported: false, show_as_preset_buttons: None }
[2024-04-03T22:45:39 INFO  govee::commands::serve] 
[2024-04-03T22:45:39 INFO  govee::commands::serve] Frigidaire Freezer (F7:99:18:1F:6C:E2:B5:1E H5179)
[2024-04-03T22:45:39 INFO  govee::commands::serve]   Platform API: devices.types.thermometer. supports_rgb=false supports_brightness=false
[2024-04-03T22:45:39 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-04-03T22:45:39 INFO  govee::commands::serve]   Undoc: room=Some("Laundry") supports_iot=false ble_only=true
[2024-04-03T22:45:39 INFO  govee::commands::serve]   Quirk { sku: "H5179", icon: "mdi:thermometer", supports_rgb: false, supports_brightness: false, color_temp_range: None, avoid_platform_api: false, ble_only: false, lan_api_capable: false, device_type: Thermometer, platform_temperature_sensor_units: Some(CelsiusTimes100), platform_humidity_sensor_units: Some(RelativePercentTimes100), iot_api_supported: false, show_as_preset_buttons: None }
[2024-04-03T22:45:39 INFO  govee::commands::serve] 
[2024-04-03T22:45:39 INFO  govee::commands::serve] Kitchen Freezer (56:DB:3F:9D:08:E3:9C:85 H5179)
[2024-04-03T22:45:39 INFO  govee::commands::serve]   Platform API: devices.types.thermometer. supports_rgb=false supports_brightness=false
[2024-04-03T22:45:39 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-04-03T22:45:39 INFO  govee::commands::serve]   Undoc: room=Some("Kitchen") supports_iot=false ble_only=true
[2024-04-03T22:45:39 INFO  govee::commands::serve]   Quirk { sku: "H5179", icon: "mdi:thermometer", supports_rgb: false, supports_brightness: false, color_temp_range: None, avoid_platform_api: false, ble_only: false, lan_api_capable: false, device_type: Thermometer, platform_temperature_sensor_units: Some(CelsiusTimes100), platform_humidity_sensor_units: Some(RelativePercentTimes100), iot_api_supported: false, show_as_preset_buttons: None }
[2024-04-03T22:45:39 INFO  govee::commands::serve] 
[2024-04-03T22:45:39 INFO  govee::commands::serve] Garage Freezer (5D:13:18:1F:68:12:1C:9D H5179)
[2024-04-03T22:45:39 INFO  govee::commands::serve]   Platform API: devices.types.thermometer. supports_rgb=false supports_brightness=false
[2024-04-03T22:45:39 INFO  govee::commands::serve]                 color_temp=None segment_rgb=None
[2024-04-03T22:45:39 INFO  govee::commands::serve]   Undoc: room=Some("Garage") supports_iot=false ble_only=true
[2024-04-03T22:45:39 INFO  govee::commands::serve]   Quirk { sku: "H5179", icon: "mdi:thermometer", supports_rgb: false, supports_brightness: false, color_temp_range: None, avoid_platform_api: false, ble_only: false, lan_api_capable: false, device_type: Thermometer, platform_temperature_sensor_units: Some(CelsiusTimes100), platform_humidity_sensor_units: Some(RelativePercentTimes100), iot_api_supported: false, show_as_preset_buttons: None }
[2024-04-03T22:45:39 INFO  govee::commands::serve] 
[2024-04-03T22:45:40 INFO  govee::service::http] http server addr is 0.0.0.0:8056
[2024-04-03T22:45:45 INFO  govee::service::hass] Wait 900ms for hass to settle on 18 entity configs
[2024-04-03T22:45:46 INFO  govee::service::hass] MQTT connected with status=CONNACK code 0: Connection Accepted.
[2024-04-03T22:45:59 INFO  govee::service::state] requesting update via Platform API LG Freezer (13:1A:18:1F:68:13:60:82 H5179) None
[2024-04-03T22:46:00 INFO  govee::service::state] requesting update via Platform API Frigidaire Freezer (F7:99:18:1F:6C:E2:B5:1E H5179) None
[2024-04-03T22:46:02 INFO  govee::service::state] requesting update via Platform API Kitchen Freezer (56:DB:3F:9D:08:E3:9C:85 H5179) None
[2024-04-03T22:46:02 INFO  govee::service::state] requesting update via Platform API Garage Freezer (5D:13:18:1F:68:12:1C:9D H5179) None

### Additional Logs

_No response_

### Home Assistant Logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by rhofour**
I believe this should fix #163, #188, and #206. It works locally for my H5179 devices.

### CODE REVIEW

**Comment by rhofour** [comment]
@wez Is there anything this is missing?

**Comment by cnewlandercvs** [comment]
> @wez Is there anything this is missing?

Is this repo maintained anymore?  Maybe just fork it and run with it until we learn otherwise.   If this repo is indeed maintained we can switch back to it.  Seems like this PR is addressing an issue three months old.  And it's been over a week waiting for this PR to be merged.

**Comment by rhofour** [comment]
It's definitely still maintained. wez replied in #206 and pointed me in exactly the right direction to fix this.

If you want to test this out yourself you're welcome to switch over to https://github.com/rhofour/govee2mqtt/tree/h5179-fix and try it out. It would probably help if other people confirmed this fixed things for them.

**Comment by wez** [comment]
@cnewlandercvs In case you are not aware, you are coming across as supremely entitled when you make a comment like that. What I expect from folks that comment on my projects is to "be excellent to each other", and to keep comments focused and productive. Your comment is neither of those things; it demonstrates a lack of awareness of the nature of the current issues, prior conversations, or how open source works, while coming across with an entitled and impatient tone. I'd encourage you to not respond to this statement or try to defend what you said. Please simply hear me and hold your peace; you needn't say any more, because it will not be a productive outcome for anyone.

**Comment by wez** [comment]
@rhofour I think this looks good, thank you! I haven't gotten around to merging it yet because I've had a lot of real life family health concerns recently, and I'll need to refresh my memory on how to correctly cut and push a release for HAOS. Merging is the easy bit!

**Comment by fhk1407** [comment]
> It's definitely still maintained. wez replied in #206 and pointed me in exactly the right direction to fix this.
> 
> If you want to test this out yourself you're welcome to switch over to https://github.com/rhofour/govee2mqtt/tree/h5179-fix and try it out. It would probably help if other people confirmed this fixed things for them.

Can you explain how to update the HAOS add-on from this?

> It's definitely still maintained. wez replied in #206 and pointed me in exactly the right direction to fix this.
> 
> If you want to test this out yourself you're welcome to switch over to https://github.com/rhofour/govee2mqtt/tree/h5179-fix and try it out. It would probably help if other people confirmed this fixed things for them.

Could you explain how to go about applying the fix to the HAOS add-on?

**Comment by alegend2k** [comment]
> > It's definitely still maintained. wez replied in #206 and pointed me in exactly the right direction to fix this.
> > If you want to test this out yourself you're welcome to switch over to https://github.com/rhofour/govee2mqtt/tree/h5179-fix and try it out. It would probably help if other people confirmed this fixed things for them.
> 
> Could you explain how to go about applying the fix to the HAOS add-on?

I also dont know how to use this in HASS - an explanation would be nice.

**Comment by amresnick** [comment]
>     If you want to test this out yourself you're welcome to switch over to https://github.com/rhofour/govee2mqtt/tree/h5179-fix >    and try it out. It would probably help if other people confirmed this fixed things for them.

>    Could you explain how to go about applying the fix to the HAOS add-on?

I would also be interested in this (until @wez has time to make the actual release).

**Comment by alegend2k** [comment]
> > ```
> > If you want to test this out yourself you're welcome to switch over to https://github.com/rhofour/govee2mqtt/tree/h5179-fix
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and try it out. It would probably help if other people confirmed this fixed things for them.
> 
> > Could you explain how to go about applying the fix to the HAOS add-on?
> 
> I would also be interested in this (until @wez has time to make the actual release).

but i cant add it to hass addon repository - if I try to add https://github.com/rhofour/govee2mqtt/tree/h5179-fix
erorr pops up

Cmd('git') failed due to: exit code(128) cmdline: git clone -v --recursive --depth=1 --shallow-submodules -- https://github.com/rhofour/govee2mqtt/tree/h5179-fix /data/addons/git/c84125d4 stderr: 'Cloning into '/data/addons/git/c84125d4'... fatal: repository 'https://github.com/rhofour/govee2mqtt/tree/h5179-fix/' not found '

**Comment by wez** [comment]
Thanks @rhofour!

**Comment by rhofour** [comment]
Thanks for merging and releasing this! I can see that all my sensors are now working as expected.

**Comment by alegend2k** [comment]
Great it is working now !! One question though - is it possible to add an offset to the sensor value ?

**Comment by buschtoens** [comment]
@alegend2k You could add a [template helper](https://www.home-assistant.io/integrations/template/) instead. For instance, here's the template helper I've been using to convert the incorrect Fahrenheit readings to Celsius:

```jinja
{% set t = states('sensor.govee_temperature') | float %}
{{ (t * 100 - 32) * (5/9) | round(1, default=0) }}
```

**Comment by fhk1407** [comment]
> Thanks for merging and releasing this! I can see that all my sensors are now working as expected.

I'm still not being served an updated add-on... I would be grateful for  an explanation on how to get it to work?

**Comment by cgoudie** [comment]
Looks like this would fix https://github.com/wez/govee2mqtt/issues/247

**Comment by Marshall-Hallenbeck** [comment]
Hmm this was merged but it still seems like it's reporting wrong for me.

**Comment by amresnick** [comment]
I don't think a build was ever released after the merge was made.

**Comment by Marshall-Hallenbeck** [comment]
Shouldn't adding the repo just use the newest code, or does it download the newest release instead?

**Comment by amresnick** [comment]
I'm not sure what happens if you're manually installing the repo in HA. If
you're installing it through the HA Add-Ons, it will install the latest
build, not the latest commit. The repo owner needs to build a new release
for these changes to come to us.

**Comment by rhofour** [comment]
> Shouldn't adding the repo just use the newest code, or does it download the newest release instead?

I believe it only downloads the newest release, but there was a release on July 13th that included this: https://github.com/wez/govee2mqtt/releases/tag/2024.07.13-82ddc6e9

I have no idea why it seems some people aren't seeing it, but I was able to update through HA Add-Ons.

**Pull request merged**
